apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: default
  annotations: {}
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - wordpress.team2.lingea.noibithackathon.cloud
      secretName: wordpress-tls
  rules:
    - host: wordpress.team2.lingea.noibithackathon.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
