## Podinfo Sample Application Kustomization

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Making sure all resources used in this tutorial are created in a dedicated namespace
# Also specific annotations are added for later identification
namespace: podinfo
commonAnnotations:
  provider: kubernetes-sample-apps

# Podinfo resources (namespace, services, deployments, etc)
resources:
  - resources/namespace.yaml
  - github.com/stefanprodan/podinfo/kustomize
