apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai-webapp
  namespace: openai
  labels:
    app: openai-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openai-webapp
  template:
    metadata:
      labels:
        app: openai-webapp
    spec:
      containers:
        - name: openai-webapp
          image: hackathonppf.azurecr.io/chatbot-webapp:0.1
          env:
            - name: REACT_APP_BACKEND_URI
              value: http://!CHANGEME!:8080
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: openai-webapp
  namespace: openai
  annotations:
    service.beta.kubernetes.io/azure-deny-all-except-load-balancer-source-ranges: "true"
spec:
  loadBalancerSourceRanges:
    - !CHANGEME!
  selector:
    app: openai-webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
